# Generated by Django 5.2.8 on 2025-11-21 05:52

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Required. Must be a valid email address.', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Nigerian phone number format: +234XXXXXXXXXX', max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Used for age-appropriate interventions', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Non-binary', 'non-binary'), ('Prefer not to say', 'prefer not to say')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, help_text='Nigerian state (e.g., Lagos, Abuja)', max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('has_previous_therapy', models.BooleanField(default=False, help_text='Has the user received therapy before?')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('yo', 'Yoruba'), ('ig', 'Igbo'), ('ha', 'Hausa'), ('pid', 'Pidgin')], default='en', max_length=10)),
                ('consent_data_storage', models.BooleanField(default=False, help_text='User consents to data storage for service delivery')),
                ('consent_anonymized_research', models.BooleanField(default=False, help_text='User consents to anonymized data use for research')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_accou_email_a9aaef_idx'), models.Index(fields=['created_at'], name='users_accou_created_71259b_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
