# Generated by Django 5.2.8 on 2025-11-24 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="User's message to the AI")),
                ('response', models.TextField(help_text="AI's response to the user")),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='SAFE', help_text='Crisis detection result', max_length=20)),
                ('primary_emotion', models.CharField(blank=True, help_text='Detected emotion (from DistilRoBERTa)', max_length=50, null=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment score from -1 (negative) to +1 (positive)', null=True)),
                ('emotion_confidence', models.FloatField(blank=True, help_text='Confidence in emotion detection (0-1)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When message was sent')),
                ('user', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='chat_chatme_user_id_fd67d9_idx'), models.Index(fields=['risk_level', '-created_at'], name='chat_chatme_risk_le_7e642f_idx'), models.Index(fields=['user', 'risk_level', '-created_at'], name='chat_chatme_user_id_db64d3_idx')],
            },
        ),
    ]
