# Generated by Django 4.2.25 on 2025-11-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('state', models.CharField(blank=True, help_text='Nigerian State', max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('hotline', 'Crisis Hotline'), ('hospital', 'Hospital/Clinic'), ('therapist', 'Therapist/Counselor'), ('support_group', 'Support Group'), ('ngo', 'NGO')], max_length=20)),
                ('availability', models.CharField(help_text='e.g., 24/7, Mon-Fri 9am-5pm', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('SAFE', 'Safe')], max_length=10)),
                ('message_content', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('alert_sent_to_admin', models.BooleanField(default=False)),
                ('alert_sent_to_contact', models.BooleanField(default=False)),
                ('resources_provided', models.ManyToManyField(blank=True, to='resources.crisisresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
